[project]
name = 'hiro-hacks'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.goose-gang]
path = 'contracts/goose-gang.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
